SELECT CASE WHEN ZEN_ORGS.ORGNAME is NULL then 'Unknown' ELSE ZEN_ORGS.ORGNAME END as COLUMN0
, ZEN_PEOPLE.NAME as COLUMN1

, ZEN_TICKETS.TICKETID as COLUMN2

, case when ZEN_TICKETS.STATUS = 'closed'

or ZEN_TICKETS.STATUS = 'solved' then 'closed' else ZEN_TICKETS.STATUS end as COLUMN3

, SUM(CASE WHEN ZEN_TICKETS.STATUS not in ('closed','solved') then 1 else 0 end) as COLUMN4

, ZEN_TICKETS.SUBJECT as COLUMN5

, CAST(ZEN_TICKETS.DATECREATED AS DATE) as COLUMN6

, CAST(ZEN_TICKETS.DATEUPDATED AS DATE) as COLUMN7

, ZEN_TICKETS.DATECREATED as COLUMN8

, ZEN_TICKETS.DATEUPDATED as COLUMN9

, ZEN_TICKETS.TAGS as COLUMN10

, case when tags like '%maas360%configuration%' then 'Configuration' when tags like '%maas360%licensing%' then 'Licensing' when tags like '%maas360%enrollment%' then 'Enrollment Issue' when tags like '%maas360%policy_update%' then 'Policy Update' when tags like '%maas360%app_dist%' then 'Application Dist' when tags like '%maas360%system_iss%' then 'System Issue' when tags like '%maas360%implementation%' then 'Implementation' when tags like '%maas360%customer_query%' then 'Customer Query' when tags like '%maas360%testing%' then 'Testing' when tags like '%maas360%documentation%' then 'Documentation' when tags like '%maas360%training%' then 'Training' else 'Other'end as COLUMN11

, ZEN_PEOPLE_2.NAME as COLUMN12

, ZEN_GROUPS.[GROUP] as COLUMN13

, ZEN_PEOPLE_3.NAME as COLUMN14

, Count(distinct ZEN_TICKETS.TICKETID) as COLUMN15

, case when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=5 then '1-5 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=10 then '6-10 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=30 then '10-30 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=90 then '31-90 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=180 then '3-6 Months' else '6 months

and over' end as COLUMN16

, DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) as COLUMN17

, case when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=5 then 1 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=10 then 2 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=30 then 3 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=90 then 4 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=180 then 5 else 6 end as COLUMN18

, ZEN_ORGS.ORG_ID as COLUMN19

, case when ZEN_TICKETS.PRIORITY is NULL then 'Not Set' else ZEN_TICKETS.PRIORITY end as COLUMN20

, ZEN_TICKETS.TICKETTYPE as COLUMN21

, CAST(ZEN_TICKETS.DUEDATE AS DATE) as COLUMN22

, CONCAT(trim(CHAR(YEAR(ZEN_TICKETS.DATECREATED))),' Wk ', trim(CHAR(datepart(wk, ZEN_TICKETS.DATECREATED)))) as COLUMN23

, YEAR(ZEN_TICKETS.DATECREATED) as COLUMN24

, datepart(wk, ZEN_TICKETS.DATECREATED) as COLUMN25

FROM dbo.ZEN_TICKETS as ZEN_TICKETS
FULL JOIN dbo.ZEN_PEOPLE as ZEN_PEOPLE_2 on ZEN_TICKETS.ASSIGNEE_ID = ZEN_PEOPLE_2.PID

LEFT OUTER JOIN dbo.ZEN_GROUPS as ZEN_GROUPS on ZEN_TICKETS.GROUP_ID = ZEN_GROUPS.GROUPID

LEFT OUTER JOIN dbo.ZEN_ORGS as ZEN_ORGS on ZEN_TICKETS.ORG_ID = ZEN_ORGS.ORG_ID

FULL JOIN dbo.ZEN_PEOPLE as ZEN_PEOPLE on ZEN_TICKETS.REQUESTED_ID = ZEN_PEOPLE.PID

FULL JOIN dbo.ZEN_PEOPLE as ZEN_PEOPLE_3 on ZEN_TICKETS.SUBMITTER_ID = ZEN_PEOPLE_3.PID

LEFT OUTER JOIN dbo.ZEN_METRICS as ZEN_METRICS on ZEN_METRICS.TICKET_ID = ZEN_TICKETS.TICKETID

LEFT OUTER JOIN dbo.ZEN_TICKETS_SOLVED_BY as ZEN_TICKETS_LATEST_SOLVED_BY_V on ZEN_TICKETS.TICKETID = ZEN_TICKETS_LATEST_SOLVED_BY_V.TICKETID
/*
LEFT OUTER JOIN dbo.CAP_TICKET_MONTHLY_REPORTING as CAP_TICKET_MONTHLY_REPORTING on ZEN_TICKETS.TICKETID = CAP_TICKET_MONTHLY_REPORTING.ZEN_TICKET_ID
*/
GROUP BY CASE WHEN ZEN_ORGS.ORGNAME is NULL then 'Unknown' ELSE ZEN_ORGS.ORGNAME END
, ZEN_PEOPLE.NAME

, ZEN_TICKETS.TICKETID

, case when ZEN_TICKETS.STATUS = 'closed'

or ZEN_TICKETS.STATUS = 'solved' then 'closed' else ZEN_TICKETS.STATUS end

, ZEN_TICKETS.SUBJECT

, CAST(ZEN_TICKETS.DATECREATED AS DATE)

, CAST (ZEN_TICKETS.DATEUPDATED AS DATE)

, ZEN_TICKETS.DATECREATED

, ZEN_TICKETS.DATEUPDATED

, ZEN_TICKETS.TAGS

, case when tags like '%maas360%configuration%' then 'Configuration' when tags like '%maas360%licensing%' then 'Licensing' when tags like '%maas360%enrollment%' then 'Enrollment Issue' when tags like '%maas360%policy_update%' then 'Policy Update' when tags like '%maas360%app_dist%' then 'Application Dist' when tags like '%maas360%system_iss%' then 'System Issue' when tags like '%maas360%implementation%' then 'Implementation' when tags like '%maas360%customer_query%' then 'Customer Query' when tags like '%maas360%testing%' then 'Testing' when tags like '%maas360%documentation%' then 'Documentation' when tags like '%maas360%training%' then 'Training' else 'Other'end

, ZEN_PEOPLE_2.NAME

, ZEN_GROUPS.[GROUP]

, ZEN_PEOPLE_3.NAME

, case when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=5 then '1-5 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=10 then '6-10 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=30 then '10-30 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=90 then '31-90 Days' when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=180 then '3-6 Months' else '6 months

and over' end

, DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED)

, case when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=5 then 1 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=10 then 2 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=30 then 3 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=90 then 4 when DATEDIFF(day, CURRENT_TIMESTAMP,ZEN_TICKETS.DATECREATED) <=180 then 5 else 6 end

, ZEN_ORGS.ORG_ID

, case when ZEN_TICKETS.PRIORITY is NULL then 'Not Set' else ZEN_TICKETS.PRIORITY end

, ZEN_TICKETS.TICKETTYPE

, CAST(ZEN_TICKETS.DUEDATE AS DATE)

, CONCAT(trim(CHAR(YEAR(ZEN_TICKETS.DATECREATED))), ' Wk ', trim(CHAR(datepart(wk, ZEN_TICKETS.DATECREATED))))

, YEAR(ZEN_TICKETS.DATECREATED)

, datepart(wk, ZEN_TICKETS.DATECREATED)